ALTER TABLE NOTIFICATIONS ADD CONSTRAINT CHECK_NOTI_TYPE
CHECK (NOTI_TYPE IN ('C', 'U', 'D', 'F'));


ALTER TABLE NOTIFICATIONS MODIFY REVIEW_ID NUMBER NULL;

ALTER TABLE NOTIFICATIONS DROP CONSTRAINT FK_NOTI_REVIEW;

ALTER TABLE NOTIFICATIONS ADD CONSTRAINT FK_NOTI_REVIEW
FOREIGN KEY (REVIEW_ID) REFERENCES REVIEWS(REVIEW_ID) ON DELETE CASCADE;


CREATE OR REPLACE TRIGGER TRG_NOTI_FOLLOW
AFTER INSERT ON FOLLOWERS
FOR EACH ROW
DECLARE
    v_notif_count NUMBER;
BEGIN
    --NO NOTI IF SOMEONE TRIES TO "FOLLOW THEMSELVES"
    IF :NEW.USER_ID != :NEW.FOLLOW_ID THEN
    
    --NOTI AMOUNT CHECK
    SELECT COUNT(*) INTO v_notif_count
    FROM NOTIFICATIONS
    WHERE USER_ID = :NEW.FOLLOW_ID;
    
    --DELETE LOGIC
    IF v_notif_count >= 5 THEN
        DELETE FROM NOTIFICATIONS
        WHERE NOTI_ID = (
            SELECT NOTI_ID
            FROM NOTIFICATIONS
            WHERE USER_ID = :NEW.FOLLOW_ID
            ORDER BY CREATED_AT ASC
            FETCH FIRST 1 ROW ONLY
        );
    END IF;
    
    --NEW NOTI INSERTION
    INSERT INTO NOTIFICATIONS(
        NOTI_ID,
        USER_ID,
        NOTI_TYPE,
        REVIEW_ID,
        ACTION_USER_ID,
        COMMENT_ID,
        IS_READ,
        CREATED_AT
        )VALUES(
            NOTIFICATION_SEQ.NEXTVAL,
            :NEW.FOLLOW_ID,
            'F',
            NULL,
            :NEW.USER_ID,
            NULL,
            0,
            SYSDATE
        );
    END IF;
EXCEPTION
    WHEN OTHERS THEN
    NULL;
END;
/

