CREATE TABLE USER_VOTE(
    user_id NUMBER NOT NULL REFERENCES USERS(user_id) ON DELETE CASCADE,
    vote_id NUMBER NOT NULL REFERENCES VOTE(vote_id) ON DELETE CASCADE,
    vote_type VARCHAR2(1) NOT NULL CHECK (vote_type IN ('U','D')),
    CONSTRAINT USER_VOTE_PK PRIMARY KEY (user_id, vote_id)
);

GRANT ALL ON ADMIN.USER_VOTE TO Andrew;