CREATE TABLE watchlist(
    list_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES USERS(user_id),
    media_id NUMBER NOT NULL,
    media_type VARCHAR2(100) NOT NULL,
    CONSTRAINT uk_user_media UNIQUE(user_id, media_id, media_type)
);

CREATE TABLE watchlist_book_mapping(
    watchlist_book_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    watchlist_book_str VARCHAR(200) NOT NULL UNIQUE
);

CREATE INDEX idx_watchlist_book_str ON watchlist_book_mapping(watchlist_book_str);


CREATE OR REPLACE FUNCTION get_watchlist_book_id(p_book_str VARCHAR2)
RETURN NUMBER
IS
    v_id NUMBER;
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    SELECT WATCHLIST_BOOK_ID INTO V_ID
    FROM WATCHLIST_BOOK_MAPPING
    WHERE WATCHLIST_BOOK_STR = P_BOOK_STR;
    RETURN V_ID;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        INSERT INTO WATCHLIST_BOOK_MAPPING(WATCHLIST_BOOK_STR)
        VALUES(P_BOOK_STR)
        RETURNING WATCHLIST_BOOK_ID INTO V_ID;
        COMMIT;
        RETURN V_ID;
    WHEN DUP_VAL_ON_INDEX THEN
        SELECT WATCHLIST_BOOK_ID INTO V_ID
        FROM WATCHLIST_BOOK_MAPPING
        WHERE WATCHLIST_BOOK_STR = P_BOOK_STR;
        RETURN V_ID;
END;
/

CREATE OR REPLACE FUNCTION GET_WATCHLIST_BOOK_STR(P_BOOK_ID NUMBER)
RETURN VARCHAR2
IS
    V_STR VARCHAR2(200);
BEGIN
    SELECT WATCHLIST_BOOK_STR INTO V_STR
    FROM WATCHLIST_BOOK_MAPPING
    WHERE WATCHLIST_BOOK_ID = P_BOOK_ID;
    RETURN V_STR;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

GRANT ALL ON ADMIN.watchlist_book_mapping TO Andrew;
GRANT ALL ON ADMIN.watchlist_book_mapping TO Joseph;
GRANT ALL ON ADMIN.watchlist TO Andrew;
GRANT ALL ON ADMIN.watchlist TO Joseph;
GRANT ALL ON ADMIN.get_watchlist_book_id TO Andrew;
GRANT ALL ON ADMIN.get_watchlist_book_id TO Joseph;
GRANT ALL ON ADMIN.GET_WATCHLIST_BOOK_STR TO Andrew;
GRANT ALL ON ADMIN.GET_WATCHLIST_BOOK_STR TO Joseph;

GRANT EXECUTE ON ADMIN.GET_WATCHLIST_BOOK_STR TO Andrew;
GRANT EXECUTE ON ADMIN.GET_WATCHLIST_BOOK_STR TO Joseph;
GRANT EXECUTE ON ADMIN.GET_WATCHLIST_BOOK_STR TO Andrew;
GRANT EXECUTE ON ADMIN.get_watchlist_book_id TO Joseph;


